services:
  - type: web
    name: my-web-service
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString

databases:
  - name: my-database
    databaseName: mydb
    user: myuser
    password: mypassword
    plan: free

